rtabmap:
  ros__parameters:
    Grid/CellSize: "0.02"
    Grid/MaxGroundAngle: "20"
    Grid/MinClusterSize: "30"
    Grid/Sensor: "2"
    Grid/RangeMin: "0.5"
    Grid/RangeMax: "15.0"
    Grid/MaxObstacleHeight: "0.6"
    Grid/RayTracing: "true"
    Grid/Scan2dUnknownSpaceFilled: "true"
    Reg/Force3DoF: "false"
    Reg/Strategy: "1"
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityByTime: "true"
    RGBD/ProximityAngle: "90"
    RGBD/ProximityDistance: "1.5"
    RGBD/ProximityPathMaxNeighbors: "100"
    RGBD/LoopClosure: "true"
    RGBD/LoopClosureMaxDistance: "15.0"
    RGBD/LoopClosureReextractFeatures: "true"
    RGBD/MaxLoopClosureDistance: "0.2"
    RGBD/NewMapOdomChangeDistance: "2.5"
    RGBD/OdomVarianceGuess: "false"
    RGBD/OdomCorrection: "true"
    RGBD/ProximityOdomGuess: "false"
    RGBD/OptimizeMaxError: "0.3"
    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/StartAtOrigin: "true"
    RGBD/LinearUpdate: "0.03"
    RGBD/AngularUpdate: "0.03"
    RGBD/LinearSpeedUpdate: "0.02"
    RGBD/AngularSpeedUpdate: "0.002"
    RGBD/CreateOccupancyGrid: "true"
    RGBD/MarkerDetection: "true"
    Marker/Dictionary: "20"
    Marker/Length: "0.3125"
    Rtabmap/StartNewMapOnGoodSignature: "false"
    Rtabmap/DetectionRate: "15"
    Rtabmap/OdomGuessRatio: "0.2"
    Mem/IncrementalMemory: "true"
    Mem/STMSize: "0"
    Mem/MaxCacheSize: "50000"
    Rtabmap/DatabaseInMemory: "true"
    Rtabmap/Threads: "8"
    Vis/Odom: "false"
    Icp/VoxelSize: "0.05"
    Icp/PointToPlaneK: "50"
    Icp/PointToPlaneRadius: "0.1"
    Icp/PointToPlane: "true"
    Icp/Iterations: "20"
    Icp/Epsilon: "0.001"
    Icp/MaxTranslation: "5"
    Icp/MaxCorrespondenceDistance: "2"
    Icp/Strategy: "1"
    Icp/OutlierRatio: "0.6"
    Icp/CorrespondenceRatio: "0.2"
    Optimizer/Strategy: "2"
    Odom/Strategy: "1"
    Odom/FilteringStrategy: "1"
    Odom/KalmanProcessNoise: "0.01"
    Odom/KalmanMeasurementNoise: "0.1"
