rtabmap:
  ros__parameters:
    Grid/CellSize: "0.02"
    Grid/MaxGroundAngle: "32"
    Grid/MinGroundHeight: "-0.05"
    Grid/MaxGroundHeight: "0.10"
    Grid/MinClusterSize: "30"
    Grid/Sensor: "2"
    Grid/RangeMin: "0.5"
    Grid/RangeMax: "15.0"
    Grid/MaxObstacleHeight: "0.6"
    Grid/RayTracing: "true"
    Grid/Scan2dUnknownSpaceFilled: "true"
    Reg/Force3DoF: "false"
    Reg/Strategy: "1"
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityByTime: "true"
    RGBD/ProximityAngle: "45"
    RGBD/ProximityDistance: "0.5"
    RGBD/ProximityPathMaxNeighbors: "10"
    RGBD/LoopClosure: "true"
    RGBD/LoopClosureMaxDistance: "15.0"
    RGBD/LoopClosureReextractFeatures: "true"
    RGBD/MaxLoopClosureDistance: "0.2"
    RGBD/NewMapOdomChangeDistance: "0"
    RGBD/OdomVarianceGuess: "false"
    RGBD/OdomCorrection: "true"
    RGBD/ProximityOdomGuess: "true"
    RGBD/OptimizeMaxError: "0.3"
    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/StartAtOrigin: "true"
    RGBD/LinearUpdate: "0.2"
    RGBD/AngularUpdate: "0.2"
    RGBD/LinearSpeedUpdate: "0.0"
    RGBD/AngularSpeedUpdate: "0.0"
    RGBD/LocalRadius: "5"
    RGBD/CreateOccupancyGrid: "true"
    Grid/FromDepth: "true"
    Grid/3D: "true"
    Grid/GroundIsObstacle: "false"
    Grid/NormalsSegmentation: "false"
    Grid/ClusterRadius: "0.1"
    Grid/FlatObstacleDetected: "true"
    GridGlobal/MinSize: "50"
    GridGlobal/UpdateError: "0.01"
    GridGlobal/OccupancyThr: "0.5"
    GridGlobal/FullUpdate: "true"
    GridGlobal/Eroded: "false"
    Mem/NotLinkedNodesKept: "false"
    RGBD/ProximityMaxGraphDepth: "5"
    RGBD/MarkerDetection: "true"
    Marker/Dictionary: "20"
    Marker/Length: "0.3125"
    Rtabmap/StartNewMapOnGoodSignature: "false"
    Rtabmap/DetectionRate: "1"
    Rtabmap/OdomGuessRatio: "0.7"
    Mem/IncrementalMemory: "true"
    Mem/STMSize: "10"
    Mem/ReduceGraph: "true"
    Mem/MaxCacheSize: "50000"
    Rtabmap/DatabaseInMemory: "true"
    Rtabmap/Threads: "8"
    Vis/Odom: "false"
    Vis/MinInliers: "15"
    Vis/MaxFeatures: "500"
    Optimizer/Strategy: "2"
    Optimizer/Iterations: "100"
    Odom/Strategy: "0"
