rtabmap:
  ros__parameters:
    Grid/CellSize: "0.04"
    Grid/MaxGroundAngle: "20"
    Grid/Sensor: "2"
    Grid/RangeMin: "0.7"
    Grid/RangeMax: "10.0"
    Grid/MaxObstacleHeight: "0.6"
    Grid/RayTracing: "true"
    Reg/Force3DoF: "false"
    Reg/Strategy: "1"
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityByTime: "true"
    RGBD/ProximityAngle: "70"
    RGBD/ProximityDistance: "1.0"
    RGBD/ProximityPathMaxNeighbors: "50"
    RGBD/LoopClosure: "true"
    RGBD/LoopClosureMaxDistance: "10.0"
    RGBD/LoopClosureReextractFeatures: "true"
    RGBD/MaxLoopClosureDistance: "0.15"
    RGBD/NewMapOdomChangeDistance: "2.0"
    RGBD/OdomVarianceGuess: "false"
    RGBD/OdomCorrection: "true"
    RGBD/ProximityOdomGuess: "false"
    RGBD/OptimizeMaxError: "0.3"
    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "false"
    RGBD/StartAtOrigin: "true"
    RGBD/LinearUpdate: "0.05"
    RGBD/AngularUpdate: "0.05"
    RGBD/LinearSpeedUpdate: "0.03"
    RGBD/AngularSpeedUpdate: "0.003"
    RGBD/CreateOccupancyGrid: "true"
    RGBD/MarkerDetection: "true"
    Marker/Dictionary: "20"
    Marker/Length: "0.3125"
    Rtabmap/StartNewMapOnGoodSignature: "false"
    Rtabmap/DetectionRate: "10"
    Rtabmap/OdomGuessRatio: "0.2"
    Vis/Odom: "false"
    Icp/VoxelSize: "0.1"
    Icp/PointToPlaneK: "20"
    Icp/PointToPlaneRadius: "0"
    Icp/PointToPlane: "true"
    Icp/Iterations: "10"
    Icp/Epsilon: "0.001"
    Icp/MaxTranslation: "3"
    Icp/MaxCorrespondenceDistance: "1"
    Icp/Strategy: "1"
    Icp/OutlierRatio: "0.7"
    Icp/CorrespondenceRatio: "0.2"
    Optimizer/Strategy: "2"
    Odom/Strategy: "1"
    Odom/FilteringStrategy: "1"
    Odom/KalmanProcessNoise: "0.01"
    Odom/KalmanMeasurementNoise: "0.1"
