/**:
  ros__parameters:
    common:
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      con_frame: false
      con_frame_num: 1
      cut_frame: false
      cut_frame_time_interval: 0.166666
      time_diff_lidar_to_imu: 0.0

    preprocess:
      lidar_type: 1
      scan_line: 4
      timestamp_unit: 3
      blind: 0.5

    mapping:
      imu_en: true
      start_in_aggressive_motion: false
      extrinsic_est_en: false
      imu_time_inte: 0.005
      satu_acc: 3.0
      satu_gyro: 35.0
      acc_norm: 1.0
      lidar_meas_cov: 0.01
      acc_cov_output: 500.0
      gyr_cov_output: 1000.0
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      imu_meas_acc_cov: 0.01
      imu_meas_omg_cov: 0.01
      gyr_cov_input: 0.01
      acc_cov_input: 0.1
      plane_thr: 0.1
      match_s: 81.0
      fov_degree: 360.0
      det_range: 100.0
      gravity_align: true
      gravity: [0.0, 0.0, -9.810]
      gravity_init: [0.0, 0.0, -9.810]
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [-1., 0., 0., 0., 1., 0., 0., 0., -1.]

    odometry:
      publish_odometry_without_downsample: false

    publish:
      path_en: true
      scan_publish_en: true
      scan_bodyframe_pub_en: true
      tf_send_en: false
      base_frame_id: "base_link"

    pcd_save:
      pcd_save_en: false
      interval: -1
