/**:
  ros__parameters:
    # Network configuration for SSH remote execution (used in real mode)
    network:
      robot_host: "192.168.1.100"  # Robot PC IP address
      robot_user: "lunabot"  # SSH username for robot PC
