/**:
  ros__parameters:
    # Network configuration for SSH remote execution (used in real mode)
    network:
      robot_host: "192.168.0.250"  # Robot PC IP address
      robot_user: "codetc"  # SSH username for robot PC
    
    # Controller configuration
    steam_mode: false  # Use Steam Deck controller mapping (true) or Xbox (false)
