rtabmap:
  ros__parameters:
    Grid/CellSize: "0.035"
    Grid/MaxGroundAngle: "10"
    Grid/Sensor: "2"
    Grid/RangeMin: "0.7"
    Grid/RangeMax: "6.0"
    Grid/MaxObstacleHeight: "0.6"
    Grid/RayTracing: "true"
    Reg/Force3DoF: "true"
    Reg/Strategy: "0"
    RGBD/ProximityBySpace: "true"
    RGBD/ProximityByTime: "false"
    RGBD/ProximityAngle: "70"
    RGBD/ProximityDistance: "0.5"
    RGBD/ProximityPathMaxNeighbors: "10"
    RGBD/LoopClosure: "true"
    RGBD/LoopClosureMaxDistance: "2.0"
    RGBD/NewMapOdomChangeDistance: "0.5"
    RGBD/OdomVarianceGuess: "false"
    RGBD/OdomCorrection: "true"
    RGBD/ProximityOdomGuess: "true"
    RGBD/OptimizeMaxError: "0.1"
    RGBD/NeighborLinkRefining: "true"
    RGBD/OptimizeFromGraphEnd: "true"
    RGBD/StartAtOrigin: "true"
    RGBD/LinearUpdate: "0.02"
    RGBD/AngularUpdate: "0.3"
    RGBD/LinearSpeedUpdate: "0.15"
    RGBD/AngularSpeedUpdate: "0.1"
    RGBD/CreateOccupancyGrid: "true"
    Rtabmap/StartNewMapOnGoodSignature: "true"
    Rtabmap/DetectionRate: "15"
    Vis/Odom: "false"
    Vis/MinInliers: "25"
    Vis/InlierDistance: "0.05"
    Vis/MaxFeatures: "3000"
    Vis/EstimationType: "0"
