kiss_icp_node:
  ros__parameters:
    # Frame settings
    base_frame: "base_link"
    lidar_odom_frame: "odom"
    publish_odom_tf: False
    publish_debug_clouds: False

    # Covariances
    position_covariance: 0.1
    orientation_covariance: 0.1

    data:
      deskew: False
      max_range: 10.0
      min_range: 0.8

    mapping:
      voxel_size: 0.5
      max_points_per_voxel: 20

    adaptive_threshold:
      initial_threshold: 2.0
      min_motion_th: 0.1

    registration:
      max_num_iterations: 500
      convergence_criterion: 0.0001
      max_num_threads: 0
