name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup workspace
      run: |
        mkdir -p ~/lunabot_ws/src/Lunabotics-2025
        cp -r . ~/lunabot_ws/src/Lunabotics-2025
        cd ~/lunabot_ws/src/Lunabotics-2025
        git submodule update --init --recursive

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y software-properties-common
        add-apt-repository universe -y
        add-apt-repository ppa:graysonarendt/sparkcan -y
        apt-get update
        apt-get install -y \
          ros-humble-rplidar-ros \
          ros-humble-realsense2-* \
          git-lfs \
          libunwind-dev \
          libgoogle-glog-dev \
          sparkcan

        source /opt/ros/humble/setup.bash
        cd ~/lunabot_ws
        rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro humble -r -y

    - name: Build
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/lunabot_ws
        export MAKEFLAGS="-j2"
        colcon build --symlink-install \
          --cmake-args \
            -DRTABMAP_SYNC_MULTI_RGBD=ON \
            -DWITH_OPENCV=ON \
            -DWITH_APRILTAG=ON \
            -DWITH_OPENGV=OFF \
          --parallel-workers 2


