name: build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

jobs:
  setup:
    runs-on: ubuntu-22.04
    name: Setup and Install Dependencies

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ROS 2 Humble manually
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
        sudo apt-get update
        sudo apt-get install -y ros-humble-desktop

    - name: Install Sensor Dependencies
      run: |
        sudo apt update
        sudo apt install -y ros-humble-rplidar-ros ros-humble-realsense2-*

    - name: Install Git LFS and Pull LFS Data
      run: |
        sudo apt update
        sudo apt install -y git-lfs
        cd src/Lunabotics-2025
        git lfs pull

    - name: Install sparkcan
      run: |
        sudo apt update
        sudo add-apt-repository ppa:graysonarendt/sparkcan -y
        sudo apt update
        sudo apt install -y sparkcan

    - name: Install ROS Dependencies Using rosdep
      run: |
        sudo rosdep init 2>/dev/null || true
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

  build:
    runs-on: ubuntu-22.04
    needs: setup
    name: Build Workspace

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ROS 2 Humble manually
      run: |
        sudo apt-get update
        sudo apt-get install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2-latest.list
        sudo apt-get update
        sudo apt-get install -y ros-humble-desktop

    - name: Build the workspace
      run: |
        source /opt/ros/humble/setup.bash
        cd ~/lunabot_ws
        colcon build --symlink-install --cmake-args -DRTABMAP_SYNC_MULTI_RGBD=ON -DWITH_OPENCV=ON -DWITH_APRILTAG=ON -DWITH_OPENGV=OFF --parallel-workers 1

